server:
  port: 10000

sv-param:
  default-url: https://158.160.23.243:8080
springdoc:
  swagger-ui:
    url: api-docs
    disable-swagger-default-url: true
logging:
  level:
    org.springframework.web: TRACE