server:
  port: 10000
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:ssl/cv5_ssl.pfx
    key-store-password: sv5-root
springdoc:
  swagger-ui:
    url: api-docs
    disable-swagger-default-url: true
logging:
  level:
    org.springframework.web: TRACE
sv-param:
  default-url: https://158.160.23.243:8080